# Generated by Django 6.0.2 on 2026-02-06 13:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subject_metadata'),
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'date')},
        ),
        migrations.AddField(
            model_name='grade',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text="AI feedback, skill tags, o'rganish yo'li"),
        ),
        migrations.AlterField(
            model_name='grade',
            name='comment',
            field=models.TextField(blank=True, help_text="O'qituvchi izohi", null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='teacher',
        ),
    ]
