# Generated by Django 6.0.2 on 2026-02-08 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Xona raqami/nomi')),
                ('capacity', models.IntegerField(verbose_name="Sig'imi")),
                ('room_type', models.CharField(choices=[('classroom', 'Sinf xonasi'), ('lab', 'Laboratoriya'), ('hall', 'Faollar zali'), ('sport', 'Sport zali'), ('meeting', 'Majlislar xonasi')], max_length=20, verbose_name='Turi')),
                ('has_projector', models.BooleanField(default=False, verbose_name='Proyektor bormi?')),
                ('has_smartboard', models.BooleanField(default=False, verbose_name='Elektron doska bormi?')),
                ('description', models.TextField(blank=True, verbose_name="Qo'shimcha jihozlar")),
            ],
            options={
                'verbose_name': 'Xona',
                'verbose_name_plural': 'Xonalar',
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('purpose', models.CharField(max_length=255, verbose_name='Maqsad (masalan: 9-A sinf, Fizika lab)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='administration.room', verbose_name='Xona')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Band qiluvchi')),
            ],
            options={
                'verbose_name': 'Xona Bandligi',
                'verbose_name_plural': 'Xona Bandliklari',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
