import re
import os

translations = {
    "Kelajak Ta'limini": "Future Education",
    "Bugun Boshqaring": "Manage Today",
    "LearnSphere - bu sun'iy intellekt yordamida o'quv jarayonini tahlil qiluvchi va boshqaruvchi innovatsion platforma.": "LearnSphere is an innovative platform that analyzes and manages the learning process using artificial intelligence.",
    "Kabinetga o'tish": "Go to Dashboard",
    "Jurnalga o'tish": "Go to Journal",
    "Boshqaruv Paneli": "Control Panel",
    "Kirish": "Login",
    "Ko'proq ma'lumot": "More Info",
    "Mening Qobiliyatlarim (AI)": "My Abilities (AI)",
    "Tanqidiy Fikrlash": "Critical Thinking",
    "Ijodkorlik": "Creativity",
    "Muloqot": "Communication",
    "Jamoaviy": "Teamwork",
    "Moslashuvchanlik": "Adaptability",
    "Ball": "Score",
    "Ma'lumotlar yo'q": "No data",
    "O'qituvchingiz hali sizning Soft Skills ko'rsatkichlaringizni kiritmagan.": "Your teacher has not entered your Soft Skills indicators yet.",
    "AI tizimida": "AI Powered",
    "LearnSphere Boshqaruv Paneli": "LearnSphere Control Panel",
    "Maktab faoliyati bir qarashda": "School activity at a glance",
    "AI Tahlil": "AI Analysis",
    "O'quvchilarning o'zlashtirishini sun'iy intellekt yordamida chuqur tahlil qiling va bashorat qiling.": "Deeply analyze and predict student achievement using AI.",
    "Ota-onalar Nazorati": "Parental Control",
    "Farzandlaringizning baholarini va davomatini onlayn kuzatib boring.": "Track your children's grades and attendance online.",
    "Elektron Jurnal": "Electronic Journal",
    "O'qituvchilar uchun qulay va tezkor baholash tizimi. Qog'ozbozlikdan xalos bo'ling.": "Convenient and fast grading system for teachers. Get rid of paperwork.",
    "Profil": "Profile",
    "Foydalanuvchi Profili": "User Profile",
    "Rasmni o'zgartirish": "Change Picture",
    "Ism": "First Name",
    "Familiya": "Last Name",
    "Telefon": "Phone",
    "Bio": "Bio",
    "Sinf": "Class",
    "Farzandlar": "Children",
    "Farzandlar biriktirilmagan.": "No children assigned.",
    "Qo'yilgan baholar": "Grades given",
    "Saqlash": "Save",
    "Bekor qilish": "Cancel",
    "AI Tahlil: Qobiliyatlar Xaritasi": "AI Analysis: Skill Map",
    "Xulosa": "Conclusion",
    "Tanqidiy fikrlash": "Critical thinking",
    "Ijodkorlik": "Creativity",
    "Muloqot": "Communication",
    "Jamoaviy ishlash": "Teamwork",
    "Moslashuvchanlik": "Adaptability",
    "So'nggi yangilanish": "Last update",
    "O'qituvchi": "Teacher",
    "O'quvchi Ko'rsatkichlari": "Student Indicators",
    "Bildirishnomalar": "Notifications",
    "Yangi": "New",
    "Sizda yangi bildirishnomalar yo'q.": "You have no new notifications.",
    "AI Assistant": "AI Assistant",
    "Teacher": "Teacher",
    "Parent": "Parent",
    "Student": "Student",
    "New Chat": "New Chat",
    "Recent Conversations": "Recent Conversations",
    "No conversations yet": "No conversations yet",
    "Select or start a new conversation": "Select or start a new conversation",
    "Start a conversation with your AI assistant": "Start a conversation with your AI assistant",
    "Type your message...": "Type your message...",
    "Send": "Send",
    "AI is thinking...": "AI is thinking...",
    "Zamonaviy Ta'lim Platformasi": "Modern Education Platform",
    "Davomat": "Attendance",
    "Davomat boshqaruvi": "Attendance Management",
    "Barcha sinflar": "All Classes",
    "Barcha holatlar": "All Statuses",
    "Kelgan": "Present",
    "Kelmagan": "Absent",
    "Kechikkan": "Late",
    "Qidirish": "Search",
    "O'quvchi": "Student",
    "Sana": "Date",
    "Holat": "Status",
    "O'zgartirish": "Change",
    "Davomat ma'lumotlari topilmadi": "Attendance data not found",
    "Oldingi": "Previous",
    "Keyingi": "Next",
    "Baholar": "Grades",
    "Baholar boshqaruvi": "Grades Management",
    "Barcha fanlar": "All Subjects",
    "O'quvchi ismi...": "Student name...",
    "Filter": "Filter",
    "Fan": "Subject",
    "Baho": "Grade",
    "Harakat": "Action",
    "Baholar topilmadi": "Grades not found",
    "Foydalanuvchilar": "Users",
    "Foydalanuvchilar boshqaruvi": "User Management",
    "Yangi foydalanuvchi": "New User",
    "Qidirish (ism, email, username)...": "Search (name, email, username)...",
    "Barcha rollar": "All Roles",
    "Ota-ona": "Parent",
    "Direktor": "Director",
    "Admin": "Admin",
    "Jami": "Total",
    "foydalanuvchi": "user",
    "O'chirish": "Delete",
    "Faollashtirish": "Activate",
    "Foydalanuvchi": "User",
    "Email": "Email",
    "Rol": "Role",
    "Status": "Status",
    "Harakatlar": "Actions",
    "Faol": "Active",
    "Nofaol": "Inactive",
    "Foydalanuvchilar topilmadi": "Users not found",
    "Tanqidiy Fikr": "Critical Thought",
    "Moslashuv": "Adaptation",
    "Sinflar Boshqaruvi": "Classes Management",
    "Yangi Sinf": "New Class",
    "o'quvchi": "student",
    "O'quvchilar": "Students",
    "Fanlar Boshqaruvi": "Subjects Management",
    "Yangi Fan": "New Subject",
    "Fan nomi": "Subject Name",
    "O'qituvchilar soni": "Teacher count",
    "o'qituvchi": "teacher",
    "Tahrirlash": "Edit",
    "Sinflar boshqaruvi": "Class management",
    "Fanlar boshqaruvi": "Subject management",
    "Boshqarish": "Manage",
    "Hozircha sinflar yo'q": "No classes yet",
    "Birinchi sinfni yarating": "Create first class",
    "Hozircha fanlar yo'q.": "No subjects yet.",
    "Birinchi fanni yarating": "Create first subject",
    "Jadval Boshqaruvi": "Schedule Management",
    "O'qituvchi Biriktiruvi": "Teacher Assignment",
    "Hisobotlar": "Reports",
    "Oila Paneli": "Family Panel",
    "Yaratish": "Create",
    "Jurnal": "Journal",
    "Vazifalar": "Assignments",
    "Haftalik o'quv rejasi va mashg'ulotlar": "Weekly lesson plan and activities",
    "Chop etish": "Print",
    "Yangi Dars": "New Lesson",
    "Barcha o'qituvchilar": "All Teachers",
    "Tozalash": "Clear",
    "Darslar yo'q": "No lessons",
    "Bu kun uchun dars jadvali hali tuzilmagan.": "Schedule for this day not set yet.",
    "Foydalanuvchini tahrirlash": "Edit User",
    "Yangi foydalanuvchi yaratish": "Create New User",
    "Admin Dashboard": "Admin Dashboard",
    "Admin Panel": "Admin Panel",
    "Yuklanmoqda...": "Loading...",
    "Muvaffaqiyatli saqlandi!": "Successfully saved!",
    "Xatolik yuz berdi!": "An error occurred!",
    "Tarmoq xatosi!": "Network error!",
    "Hech narsa tanlanmagan!": "Nothing selected!",
    "ni o'chirishga ishonchingiz komilmi?": " are you sure you want to delete?",
    "Muvaffaqiyatli o'chirildi!": "Successfully deleted!",
    "Yangi": "New",
    "chat": "chat",
    "K": "P",
    "Kish": "L",
    "Yo'q": "A",
    "O'qituvchilarni biriktirish": "Assign Teachers",
    "Yangi biriktiruv": "New Assignment",
    "Mavjud biriktiruvlar": "Existing Assignments",
    "Biriktirish": "Assign",
    "Haqiqatan ham o'chirmoqchimisiz?": "Are you sure you want to delete?",
    "Hozircha biriktiruvlar yo'q": "No assignments yet",
    "Fanni tahrirlash": "Edit Subject",
    "Yangi fan yaratish": "Create New Subject",
    "Barcha ma'lumotlar o'chiriladi": "All data will be deleted",
    "Ha, o'chirish": "Yes, delete",
    "Fanga tegishli barcha baholar o'chiriladi": "All grades for the subject will be deleted",
    "Sinfdagi barcha o'quvchilar sinfdan chiqariladi": "All students will be removed from the class",
    "Sinfni o'chirish": "Delete Class",
    "Fanni o'chirish": "Delete Subject",
    "Foydalanuvchini o'chirish": "Delete User",
    "Sinfni tahrirlash": "Edit Class",
    "Yangi sinf yaratish": "Create New Class",
    "Sinfni o'chirishga ishonchingiz komilmi?": "Are you sure you want to delete the class?",
    "Sinf o'chirildi!": "Class deleted!",
    "Xatolik!": "Error!",
    "fanini o'chirishga ishonchingiz komilmi?": " are you sure you want to delete the subject?",
    "Fan o'chirildi!": "Subject deleted!",
    "Bahoni o'chirishga ishonchingiz komilmi?": "Are you sure you want to delete the grade?",
    "Baho o'chirildi!": "Grade deleted!",
    "Davomat yangilandi!": "Attendance updated!",
    "Tayinlash bekor qilindi!": "Assignment canceled!",
    "Hozircha yangi foydalanuvchilar yo'q": "No new users yet",
}

po_path = 'locale/en/LC_MESSAGES/django.po'

if not os.path.exists(po_path):
    print(f"Error: {po_path} not found!")
    exit(1)

with open(po_path, 'r', encoding='utf-8') as f:
    content = f.read()

def replace_func(match):
    msgid = match.group(1)
    if msgid in translations:
        return f'msgid "{msgid}"\nmsgstr "{translations[msgid]}"'
    return match.group(0)

new_content = re.sub(r'msgid "(.*?)"\nmsgstr ""', replace_func, content)

with open(po_path, 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f"Successfully updated {po_path} with {len(translations)} potential translations.")
