import re
import os

translations = {
    "Kelajak Ta'limini": "Образование Будущего",
    "Bugun Boshqaring": "Управляйте Сегодня",
    "LearnSphere - bu sun'iy intellekt yordamida o'quv jarayonini tahlil qiluvchi va boshqaruvchi innovatsion platforma.": "LearnSphere - инновационная платформа, анализирующая и управляющая процессом обучения с помощью искусственного интеллекта.",
    "Kabinetga o'tish": "Перейти в кабинет",
    "Jurnalga o'tish": "Перейти в журнал",
    "Boshqaruv Paneli": "Панель управления",
    "Kirish": "Вход",
    "Ko'proq ma'lumot": "Подробнее",
    "Mening Qobiliyatlarim (AI)": "Мои способности (AI)",
    "Tanqidiy Fikrlash": "Критическое мышление",
    "Ijodkorlik": "Креативность",
    "Muloqot": "Коммуникация",
    "Jamoaviy": "Командная работа",
    "Moslashuvchanlik": "Адаптивность",
    "Ball": "Балл",
    "Ma'lumotlar yo'q": "Нет данных",
    "O'qituvchingiz hali sizning Soft Skills ko'rsatkichlaringizni kiritmagan.": "Ваш преподаватель еще не ввел ваши показатели Soft Skills.",
    "AI tizimida": "На базе ИИ",
    "LearnSphere Boshqaruv Paneli": "Панель управления LearnSphere",
    "Maktab faoliyati bir qarashda": "Деятельность школы с одного взгляда",
    "AI Tahlil": "AI Анализ",
    "O'quvchilarning o'zlashtirishini sun'iy intellekt yordamida chuqur tahlil qiling va bashorat qiling.": "Глубоко анализируйте и прогнозируйте успеваемость учащихся с помощью ИИ.",
    "Ota-onalar Nazorati": "Родительский контроль",
    "Farzandlaringizning baholarini va davomatini onlayn kuzatib boring.": "Следите за оценками и посещаемостью ваших детей онлайн.",
    "Elektron Jurnal": "Электронный журнал",
    "O'qituvchilar uchun qulay va tezkor baholash tizimi. Qog'ozbozlikdan xalos bo'ling.": "Удобная и быстрая система оценивания для учителей. Избавьтесь от бумажной волокиты.",
    "Profil": "Профиль",
    "Foydalanuvchi Profili": "Профиль пользователя",
    "Rasmni o'zgartirish": "Сменить фото",
    "Ism": "Имя",
    "Familiya": "Фамилия",
    "Telefon": "Телефон",
    "Bio": "О себе",
    "Sinf": "Класс",
    "Farzandlar": "Дети",
    "Farzandlar biriktirilmagan.": "Дети не прикреплены.",
    "Qo'yilgan baholar": "Поставленные оценки",
    "Saqlash": "Сохранить",
    "Bekor qilish": "Отмена",
    "AI Tahlil: Qobiliyatlar Xaritasi": "AI Анализ: Карта способностей",
    "Xulosa": "Заключение",
    "Tanqidiy fikrlash": "Критическое мышление",
    "Ijodkorlik": "Креативность",
    "Muloqot": "Коммуникация",
    "Jamoaviy ishlash": "Командная работа",
    "Moslashuvchanlik": "Адаптивность",
    "So'nggi yangilanish": "Последнее обновление",
    "O'qituvchi": "Учитель",
    "O'quvchi Ko'rsatkichlari": "Показатели ученика",
    "Bildirishnomalar": "Уведомления",
    "Yangi": "Новый",
    "Sizda yangi bildirishnomalar yo'q.": "У вас нет новых уведомлений.",
    "AI Assistant": "AI Ассистент",
    "Teacher": "Учитель",
    "Parent": "Родитель",
    "Student": "Ученик",
    "New Chat": "Новый чат",
    "Recent Conversations": "Недавние диалоги",
    "No conversations yet": "Пока нет диалогов",
    "Select or start a new conversation": "Выберите или начните новый диалог",
    "Start a conversation with your AI assistant": "Начните диалог с вашим AI ассистентом",
    "Type your message...": "Введите сообщение...",
    "Send": "Отправить",
    "AI is thinking...": "AI думает...",
    "Zamonaviy Ta'lim Platformasi": "Современная образовательная платформа",
    "Davomat": "Посещаемость",
    "Davomat boshqaruvi": "Управление посещаемостью",
    "Barcha sinflar": "Все классы",
    "Barcha holatlar": "Все статусы",
    "Kelgan": "Пришел",
    "Kelmagan": "Не пришел",
    "Kechikkan": "Опоздал",
    "Qidirish": "Поиск",
    "O'quvchi": "Ученик",
    "Sana": "Дата",
    "Holat": "Статус",
    "O'zgartirish": "Изменить",
    "Davomat ma'lumotlari topilmadi": "Данные о посещаемости не найдены",
    "Oldingi": "Назад",
    "Keyingi": "Вперед",
    "Baholar": "Оценки",
    "Baholar boshqaruvi": "Управление оценками",
    "Barcha fanlar": "Все предметы",
    "O'quvchi ismi...": "Имя ученика...",
    "Filter": "Фильтр",
    "Fan": "Предмет",
    "Baho": "Оценка",
    "Harakat": "Действие",
    "Baholar topilmadi": "Оценки не найдены",
    "Foydalanuvchilar": "Пользователи",
    "Foydalanuvchilar boshqaruvi": "Управление пользователями",
    "Yangi foydalanuvchi": "Новый пользователь",
    "Qidirish (ism, email, username)...": "Поиск (имя, email, username)...",
    "Barcha rollar": "Все роли",
    "O'qituvchi": "Учитель",
    "Ota-ona": "Родитель",
    "Direktor": "Директор",
    "Admin": "Админ",
    "Jami": "Всего",
    "foydalanuvchi": "пользователей",
    "O'chirish": "Удалить",
    "Faollashtirish": "Активировать",
    "Foydalanuvchi": "Пользователь",
    "Email": "Email",
    "Rol": "Роль",
    "Status": "Статус",
    "Harakatlar": "Действия",
    "Faol": "Активен",
    "Nofaol": "Неактивен",
    "Foydalanuvchilar topilmadi": "Пользователи не найдены",
    "Birinchi": "Первый",
    "Oxirgi": "Последний",
    "Tanqidiy Fikr": "Критическое мышление",
    "Ijodkorlik": "Креативность",
    "Muloqot": "Коммуникация",
    "Jamoaviy": "Командная работа",
    "Moslashuv": "Адаптивность",
    "Sinflar Boshqaruvi": "Управление классами",
    "Yangi Sinf": "Новый класс",
    "o'quvchi": "учеников",
    "O'quvchilar": "Ученики",
    "Fanlar Boshqaruvi": "Управление предметами",
    "Yangi Fan": "Новый предмет",
    "Fan nomi": "Название предмета",
    "O'qituvchilar soni": "Количество учителей",
    "o'qituvchi": "учителей",
    "Tahrirlash": "Редактировать",
    "Sinflar boshqaruvi": "Управление классами",
    "Fanlar boshqaruvi": "Управление предметами",
    "Boshqarish": "Управление",
    "Hozircha sinflar yo'q": "Классов пока нет",
    "Birinchi sinfni yarating": "Создайте первый класс",
    "Yangi fan": "Новый предмет",
    "Hozircha fanlar yo'q.": "Предметов пока нет.",
    "Birinchi fanni yarating": "Создайте первый предмет",
    "Jadval Boshqaruvi": "Управление расписанием",
    "O'qituvchi Biriktiruvi": "Прикрепление учителей",
    "Hisobotlar": "Отчеты",
    "Oila Paneli": "Семейная панель",
    "Yaratish": "Создать",
    "Jurnal": "Журнал",
    "Vazifalar": "Задания",
    "Haftalik o'quv rejasi va mashg'ulotlar": "Еженедельный учебный план и занятия",
    "Chop etish": "Печать",
    "Yangi Dars": "Новый урок",
    "Barcha sinflar": "Все классы",
    "Barcha o'qituvchilar": "Все учителя",
    "Tozalash": "Очистить",
    "Darslar yo'q": "Уроков нет",
    "Bu kun uchun dars jadvali hali tuzilmagan.": "Расписание на этот день еще не составлено.",
    "Foydalanuvchini tahrirlash": "Редактировать пользователя",
    "Yangi foydalanuvchi yaratish": "Создать нового пользователя",
    "Bekor qilish": "Отмена",
    "Saqlash": "Сохранить",
    "Admin Dashboard": "Панель администратора",
    "Admin Panel": "Админ панель",
    "Yuklanmoqda...": "Загрузка...",
    "Muvaffaqiyatli saqlandi!": "Успешно сохранено!",
    "Xatolik yuz berdi!": "Произошла ошибка!",
    "Tarmoq xatosi!": "Сетевая ошибка!",
    "Hech narsa tanlanmagan!": "Ничего не выбрано!",
    "ni o'chirishga ishonchingiz komilmi?": "вы уверены, что хотите удалить?",
    "Muvaffaqiyatli o'chirildi!": "Успешно удалено!",
    "Yangi": "Новый",
    "chat": "чат",
    "K": "Пр",
    "Kish": "Оп",
    "Yo'q": "Н/б",
    "O'qituvchilarni biriktirish": "Прикрепление учителей",
    "Yangi biriktiruv": "Новое прикрепление",
    "Mavjud biriktiruvlar": "Существующие прикрепления",
    "Biriktirish": "Прикрепить",
    "Haqiqatan ham o'chirmoqchimisiz?": "Вы действительно хотите удалить?",
    "Hozircha biriktiruvlar yo'q": "Прикреплений пока нет",
    "Fanni tahrirlash": "Редактировать предмет",
    "Yangi fan yaratish": "Создать новый предмет",
    "Barcha ma'lumotlar o'chiriladi": "Все данные будут удалены",
    "Ha, o'chirish": "Да, удалить",
    "Fanga tegishli barcha baholar o'chiriladi": "Все оценки по предмету будут удалены",
    "Sinfdagi barcha o'quvchilar sinfdan chiqariladi": "Все ученики будут исключены из класса",
    "Sinfni o'chirish": "Удалить класс",
    "Fanni o'chirish": "Удалить предмет",
    "Foydalanuvchini o'chirish": "Удалить пользователя",
    "Sinfni tahrirlash": "Реdaктировать класс",
    "Yangi sinf yaratish": "Создать новый класс",
    "Sinfni o'chirishga ishonchingiz komilmi?": "Вы уверены, что хотите удалить класс?",
    "Sinf o'chirildi!": "Класс удален!",
    "Xatolik!": "Ошибка!",
    "fanini o'chirishga ishonchingiz komilmi?": "вы уверены, что хотите удалить предмет?",
    "Fan o'chirildi!": "Предмет удален!",
    "Bahoni o'chirishga ishonchingiz komilmi?": "Вы уверены, что хотите удалить оценку?",
    "Baho o'chirildi!": "Оценка удалена!",
    "Davomat yangilandi!": "Посещаемость обновлена!",
    "Tayinlash bekor qilindi!": "Назначение отменено!",
    "Hozircha yangi foydalanuvchilar yo'q": "Новых пользователей пока нет",
    "Mahsulotni Tahrirlash": "Редактировать товар",
    "Saqlanmoqda...": "Сохранение...",
    "Xatolik yuz berdi": "Произошла ошибка",
    "Tarmoq xatosi": "Сетевая ошибка",
    "Haqiqatan ham bu mahsulotni o'chirmoqchimisiz?": "Вы действительно хотите удалить этот товар?",
    "Mahsulotlar mavjud emas": "Товары отсутствуют",
    "Moddiy": "Материальный",
    "Raqamli": "Цифровой",
    "Faol emas": "Неактивен",
    "So'rovlar mavjud emas": "Запросов нет",
    "Tasdiqlash": "Подтвердить",
    "Rad etish": "Отклонить",
    "Tasdiqlaysizmi?": "Подтверждаете?",
    "Rad etasizmi?": "Отклоняете?",
    "Tayinlashni bekor qilishga ishonchingiz komilmi?": "Вы уверены, что хотите отменить назначение?",
    "sinfni o'chirishga ishonchingiz komilmi?": "вы уверены, что хотите удалить класс?",
}

po_path = 'locale/ru/LC_MESSAGES/django.po'

if not os.path.exists(po_path):
    print(f"Error: {po_path} not found!")
    exit(1)

with open(po_path, 'r', encoding='utf-8') as f:
    content = f.read()

def replace_func(match):
    msgid = match.group(1)
    if msgid in translations:
        return f'msgid "{msgid}"\nmsgstr "{translations[msgid]}"'
    return match.group(0)

# Pattern to find empty msgstr for specific msgid
new_content = re.sub(r'msgid "(.*?)"\nmsgstr ""', replace_func, content)

with open(po_path, 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f"Successfully updated {po_path} with {len(translations)} potential translations.")
