# Generated by Django 6.0.2 on 2026-02-06 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50, verbose_name='Xona')),
                ('day_of_week', models.CharField(choices=[('monday', 'Dushanba'), ('tuesday', 'Seshanba'), ('wednesday', 'Chorshanba'), ('thursday', 'Payshanba'), ('friday', 'Juma'), ('saturday', 'Shanba')], max_length=10, verbose_name='Kun')),
                ('start_time', models.TimeField(verbose_name='Boshlanish vaqti')),
                ('end_time', models.TimeField(verbose_name='Tugash vaqti')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.class', verbose_name='Sinf')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.subject', verbose_name='Fan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Jadval',
                'verbose_name_plural': 'Jadvallar',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
    ]
