# Generated by Django 6.0.2 on 2026-02-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Kompetensiya xaritasi, AI tutor sozlamalari'),
        ),
    ]
