# Generated by Django 6.0.2 on 2026-02-08 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_subject_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('critical_thinking', models.IntegerField(default=0, verbose_name='Tanqidiy fikrlash')),
                ('creativity', models.IntegerField(default=0, verbose_name='Ijodkorlik')),
                ('communication', models.IntegerField(default=0, verbose_name='Muloqot')),
                ('teamwork', models.IntegerField(default=0, verbose_name='Jamoaviy ishlash')),
                ('adaptive_learning', models.IntegerField(default=0, verbose_name='Moslashuvchanlik')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_map', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qobiliyatlar Xaritasi',
                'verbose_name_plural': 'Qobiliyatlar Xaritalari',
            },
        ),
        migrations.CreateModel(
            name='StudentInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_score', models.IntegerField(default=0, help_text='Qiziqish darajasi (0-100)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_interests', to='core.subject')),
            ],
            options={
                'verbose_name': "O'quvchi Qiziqishi",
                'verbose_name_plural': "O'quvchi Qiziqishlari",
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
