# Generated by Django 6.0.2 on 2026-02-06 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_bio_user_phone_user_profile_picture'),
    ]

    operations = [
    ]
