# Generated by Django 6.0.2 on 2026-02-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20260206_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='AI tutor preferences, kompetensiya xaritasi'),
        ),
    ]
