# Generated by Django 6.0.2 on 2026-02-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinemeeting',
            name='audience',
            field=models.CharField(choices=[('class', 'Specific Class'), ('teachers', 'All Teachers'), ('parents', 'All Parents')], default='class', max_length=20),
        ),
    ]
