# Generated by Django 6.0.2 on 2026-02-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap icon class (e.g., bi-star)', max_length=50),
        ),
        migrations.AddField(
            model_name='reward',
            name='type',
            field=models.CharField(choices=[('physical', 'Moddiy narsa'), ('digital', "Raqamli rag'bat"), ('privilege', 'Imkoniyat')], default='physical', max_length=20),
        ),
    ]
