# Generated by Django 6.0.2 on 2026-02-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_reward_icon_reward_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='is_equipped',
            field=models.BooleanField(default=False),
        ),
    ]
