# Generated by Django 6.0.2 on 2026-02-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=0, help_text="0 = cheklov yo'q", verbose_name='Vaqt cheklovi (daqiqa)'),
        ),
    ]
